// This file was generated by react-native-wix-engine on Wed Oct 07 2020
// You can extend it if you want, but leave the defaults to be required from the engine config

module.exports = {
  ...require('./node_modules/react-native-wix-engine/tools/engine_cli/etc/metro.config')
};
